### ISSUE TITLE
empty stone cutter

### ISSUE THREAD

**Issue by PiTTl** [JoseDouglas26/breeze_blocks#1]
sorry, it's me again.
How do I get these blocks?
Nothing is available in my stone cutter
![beton](https://github.com/user-attachments/assets/ccfef3d4-eea6-48fb-9eb0-792451c9b1a0)

**Comment by PiTTl** [comment]
take your time, there's no rush.
but I'm looking forward to using it on my server. They look very pretty  (like your other additons to Mineclonia) :+1:

**Comment by JoseDouglas26** [comment]
Everything should be working now. Mineclonia forces the modder to manually add the blocks to the stonecuttable group. The only thing I didn't like about this mod was the placement of the blocks. If you have any problems with this, don't hesitate to report it. Suggestions are also welcome.
